import assert from 'node:assert/strict'
import { createServer } from 'node:http'
import test from 'node:test'
import { registerKnowledgeWeb } from '../lib/web.js'

test('management console serves a secured same-origin application', async (t) => {
  let route
  const ctx = {
    webServer: {
      register(value) {
        route = value
        return () => { route = undefined }
      },
    },
    get() { return undefined },
  }
  const dispose = registerKnowledgeWeb(ctx, '/knowledge', '/knowledge-local/v1', 'same-origin', 'desktop-embed-token')
  assert.equal(route.kind, 'prefix')
  assert.equal(route.path, '/knowledge')
  const server = createServer((req, res) => void route.handler(req, res))
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  const address = server.address()
  const base = `http://127.0.0.1:${address.port}`
  t.after(async () => {
    dispose()
    await new Promise(resolve => server.close(resolve))
  })

  const index = await fetch(`${base}/knowledge`)
  assert.equal(index.status, 200)
  assert.equal(index.headers.get('x-frame-options'), 'SAMEORIGIN')
  assert.match(index.headers.get('content-security-policy'), /frame-ancestors 'self'/)
  const html = await index.text()
  assert.match(html, /name="dsh-knowledge-api" content="\/knowledge-local\/v1"/)
  assert.match(html, /name="dsh-knowledge-auth-mode" content="same-origin"/)
  assert.match(html, /src="\/knowledge\/app\.js\?v=[a-f0-9]{12}"/)
  assert.match(html, /src="\/knowledge\/markdown-preview\.js\?v=[a-f0-9]{12}"/)
  assert.match(html, /href="\/knowledge\/styles\.css\?v=[a-f0-9]{12}"/)
  assert.equal(index.headers.get('cache-control'), 'no-store')

  const script = await fetch(`${base}/knowledge/app.js`)
  assert.equal(script.status, 200)
  assert.match(script.headers.get('content-type'), /text\/javascript/)
  assert.equal(script.headers.get('cache-control'), 'public, max-age=31536000, immutable')
  const application = await script.text()
  assert.match(application, /sessionStorage/)
  assert.match(application, /api\('documents'\)/)
  assert.match(application, /note-workspace/)
  assert.match(application, /note-tree-panel/)
  assert.match(application, /note-tree-base/)
  assert.match(application, /note-tree-document/)
  assert.match(application, /note-editor/)
  assert.match(application, /note-title-input/)
  assert.match(application, /note-body-editor/)
  assert.match(application, /DshKnowledgeMarkdown\.renderMarkdown/)
  assert.match(application, /markdown-table-scroll/)
  assert.match(application, /表格内容，可横向滚动/)
  assert.match(application, /note-mode-switch/)
  assert.match(application, /data-tree-open/)
  assert.match(application, /note-tree-scrim/)
  assert.match(application, /saveDocumentEditor/)
  assert.match(application, /createBlankDocument/)
  assert.match(application, /function documentKnowledgeBases/)
  assert.match(application, /function openKnowledgeBaseDocuments/)
  assert.match(application, /function renderKnowledgeBaseDetail/)
  assert.match(application, /documents\?knowledgeBaseId=/)
  assert.match(application, /libraryDetail/)
  assert.doesNotMatch(application, /inspectedKnowledgeBaseId/)
  assert.match(application, /mounts\/resolve/)
  assert.match(application, /当前会话未挂载知识库/)
  assert.match(application, /confirmDeleteDocument/)
  assert.match(application, /openFinalizeDocument/)
  assert.match(application, /reopenDocument/)
  assert.match(application, /已收集完成/)
  assert.match(application, /editor-save-status/)
  assert.doesNotMatch(application, /renderDocumentModeTabs|renderLegacyEntries/)
  assert.match(application, /app-sidebar-resizer/)
  assert.doesNotMatch(application, /视图设置|openLayoutEditor|layoutRangeField/)
  assert.match(application, /pane-toggle-button/)
  assert.match(application, /aria-pressed/)
  assert.match(application, /workspace-switcher/)
  assert.match(application, /knowledgeBaseQuery/)
  assert.match(application, /writebackPolicy/)
  assert.match(application, /openGlobalWritebackModelEditor/)
  assert.match(application, /严谨/)
  assert.match(application, /主动/)
  assert.match(application, /loading-skeleton/)
  assert.match(application, /data-sidebar-hidden/)
  assert.match(application, /永久删除/)
  assert.match(application, /输入知识库名称确认/)
  assert.match(application, /x-dsh-knowledge-client/)
  assert.match(application, /远程知识库 API/)
  assert.match(application, /复制地址/)
  assert.match(application, /开启远程 API/)
  assert.match(application, /已撤销令牌已永久删除/)
  assert.match(application, /captureScrollPosition/)
  assert.match(application, /restoreScrollPosition/)
  assert.match(application, /data-scroll-key/)
  assert.match(application, /host-theme-ready/)
  assert.match(application, /event\.source !== window\.parent/)
  assert.match(application, /parentOrigin && event\.origin !== parentOrigin/)
  assert.match(application, /CSS\.supports\('color'/)
  assert.match(application, /root\.style\.colorScheme/)
  assert.match(application, /installHostThemeBridge\(\)\.then\(\(\) => boot\(\)\)/)

  const stylesheet = await fetch(`${base}/knowledge/styles.css`)
  assert.equal(stylesheet.status, 200)
  const styles = await stylesheet.text()
  assert.match(styles, /data-sidebar-hidden="true"/)
  assert.match(styles, /\.note-workspace/)
  assert.match(styles, /\.note-tree-panel \{[\s\S]*min-height: 0;[\s\S]*height: 100%;[\s\S]*overflow: hidden;/)
  assert.match(styles, /\.note-tree \{[\s\S]*overflow-y: auto;/)
  assert.match(styles, /\.note-editor \{[\s\S]*height: 100%;[\s\S]*overflow: hidden;/)
  assert.match(styles, /\.note-editor-toolbar \{[\s\S]*z-index: 2;[\s\S]*background: var\(--surface\);/)
  assert.match(styles, /\.note-editor-scroll \{[\s\S]*overflow: auto;[\s\S]*overscroll-behavior: contain;/)
  assert.match(styles, /\.tree-folder-icon \{[\s\S]*mask: url\("data:image\/svg\+xml/)
  assert.match(styles, /\.note-tree-group\[data-expanded="true"\] \.tree-folder-icon/)
  assert.match(styles, /\.tree-document-icon \{[\s\S]*mask: url\("data:image\/svg\+xml/)
  assert.match(styles, /\.note-tree-document\[aria-current="page"\] \.tree-document-icon/)
  assert.match(styles, /\.markdown-preview/)
  assert.match(styles, /\.markdown-table-scroll \{[\s\S]*overflow-x: auto/)
  assert.match(styles, /\.note-editor \{[\s\S]*container-name: note-editor;[\s\S]*container-type: inline-size;/)
  assert.match(styles, /\.note-editor-actions \{[\s\S]*flex-wrap: wrap;/)
  assert.match(styles, /@container note-editor \(max-width: 700px\)/)
  assert.match(styles, /@container note-editor \(max-width: 480px\)/)
  assert.match(styles, /\.document-finalized-banner/)
  assert.match(styles, /container-type: inline-size/)
  assert.match(styles, /note-workspace\[data-tree-open="true"\]/)
  assert.match(styles, /background: var\(--dialog-surface\)/)
  assert.match(styles, /\.input, \.select \{ height: 40px/)
  assert.match(styles, /scrollbar-color: var\(--scrollbar-thumb\) transparent/)
  assert.match(styles, /input\[type="checkbox"\],[\s\S]*appearance: none;/)
  assert.match(styles, /input\[type="checkbox"\]:checked,[\s\S]*background: var\(--accent\)/)
  assert.match(styles, /\.select \{[\s\S]*appearance: none;[\s\S]*background-image:/)
  assert.match(styles, /\.range-row input\[type="range"\]::-webkit-slider-thumb/)
  assert.match(styles, /\.archived-bases summary::-webkit-details-marker/)
  assert.match(styles, /grid-template-columns: subgrid/)
  assert.match(styles, /\.library-detail-header/)
  assert.match(styles, /\[data-base-detail="true"\]/)
  const shellSource = application.slice(application.indexOf('function renderShell()'), application.indexOf('function renderSidebar()'))
  assert.doesNotMatch(shellSource, /新建知识库|新建知识/)
  const sidebarSource = application.slice(application.indexOf('function renderSidebar()'), application.indexOf('function renderCurrentView()'))
  assert.match(sidebarSource, /知识工作区/)
  assert.match(sidebarSource, /知识库与挂载/)
  assert.doesNotMatch(sidebarSource, /interfaceIcon|nav-icon/)
  const documentsSource = application.slice(application.indexOf('function renderEntries()'), application.indexOf('function renderCandidates()'))
  assert.match(documentsSource, /note-tree-search/)
  assert.match(documentsSource, /新建文档/)
  assert.doesNotMatch(documentsSource, /条目管理/)
  const knowledgeBaseCardSource = application.slice(application.indexOf('function renderKnowledgeBaseCard('), application.indexOf('function findExplicitMount('))
  assert.match(knowledgeBaseCardSource, /查看知识/)
  assert.match(knowledgeBaseCardSource, /openKnowledgeBaseDocuments/)
  assert.doesNotMatch(knowledgeBaseCardSource, /navigate\('entries'\)/)
  assert.match(application, /function openSheet/)
  assert.match(styles, /dialog\.sheet/)

  const markdownPreview = await fetch(`${base}/knowledge/markdown-preview.js`)
  assert.equal(markdownPreview.status, 200)
  assert.match(markdownPreview.headers.get('content-type'), /text\/javascript/)
  assert.equal(markdownPreview.headers.get('cache-control'), 'public, max-age=31536000, immutable')
  assert.match(await markdownPreview.text(), /DshKnowledgeMarkdown/)

  const embedded = await fetch(`${base}/knowledge?embed=desktop-embed-token`)
  assert.equal(embedded.status, 200)
  assert.equal(embedded.headers.get('x-frame-options'), null)
  assert.doesNotMatch(embedded.headers.get('content-security-policy'), /frame-ancestors/)

  const invalidEmbed = await fetch(`${base}/knowledge?embed=wrong-token`)
  assert.equal(invalidEmbed.status, 200)
  assert.equal(invalidEmbed.headers.get('x-frame-options'), 'SAMEORIGIN')
  assert.match(invalidEmbed.headers.get('content-security-policy'), /frame-ancestors 'self'/)

  const missing = await fetch(`${base}/knowledge/not-found.js`)
  assert.equal(missing.status, 404)
  const post = await fetch(`${base}/knowledge`, { method: 'POST' })
  assert.equal(post.status, 405)
})
